spring.application.name=NoSQL MongodbL -demo

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=userdb
logging.config=classpath:log4j2.xml
server.port=8080